
language: haskell
# these installs are to ensure test environment is consistent across
# all smaccm project travis tests:
install:
  - cabal install cabal-install
  - cabal install alex
  - cabal install happy
script:
  - ghc --version
  - cabal --version
  - make create-sandbox
  - make
ghc:
  - 7.8
